--https://programmers.co.kr/learn/courses/30/lessons/59412

SELECT HOUR, COUNT(*) COUNT
FROM(SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) HOUR FROM ANIMAL_OUTS)
WHERE HOUR BETWEEN 09 AND 19
GROUP BY HOUR
ORDER BY HOUR ASC